language: android                                                # 语言说明
jdk: openjdk11
dist: trusty                                                     # Android 项目的编译坏境

before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.2"

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools

    # The SDK version used to compile your project
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew

script: 
  - ./gradlew assembleRelease
